name: Vagrant Up

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vagrant-up:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      # Installing this is skipped in CI as using it was causing some corruption in
      # attempting to mount the shared folder. The guest and host guest additions
      # versions are close enough that we are fine without it.
      # - run: vagrant plugin install vagrant-vbguest
      # - run: NO_SUBMISSIONS=1 vagrant up ubuntu-22.04
      # - name: Validate image
      #   run: curl --show-error --fail --include http://localhost:1511

      - name: failed step
        run: |
          exit 1
      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          # Literal body:
          body: Build job of ${{github.repository}} Failed!
          # Read file contents as body:
          # body: file://README.md
          to: reapernsgaming@gmail.com
          from: Github action # <user@example.com>
          # Optional content type (defaults to text/plain):
          # content_type: text/html
          # Optional attachments:
          # attachments: attachments.zip,git.diff,./dist/static/main.js
